In [1]:
import numpy as np

In [2]:
# Vector/list/array

In [3]:
array = np.array([1,2,3,4,5,6,7,8])

print(array)

[1 2 3 4 5 6 7 8]


In [4]:
type(array)

numpy.ndarray

In [5]:
# check dimension of array

array.ndim

1

In [18]:
array.shape

(10,)

In [6]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#python list
l = range(10000)
%timeit [i**2 for i in l]

5.41 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
#np.array
a = np.arange(10000)
%timeit a**2

14.5 µs ± 383 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [106]:
#2D array
#array of arrays

array_2d = np.array([[1,2,3],[5,6,7]])
print(array_2d)

[[1 2 3]
 [5 6 7]]


In [107]:
print(array_2d.ndim)
print(array_2d.shape)

2
(2, 3)


In [108]:
#Aaray Transpose

array_2d = array_2d.T
array_2d

array([[1, 5],
       [2, 6],
       [3, 7]])

In [109]:
print(array_2d.ndim)
print(array_2d.shape)

2
(3, 2)


In [23]:
#3D array

array_3d = np.array([[[1,2,3],[5,6,7]],[[10,20,30],[50,60,70]]])
print(array_3d)

[[[ 1  2  3]
  [ 5  6  7]]

 [[10 20 30]
  [50 60 70]]]


In [24]:
print(array_3d.ndim)
print(array_3d.shape)

3
(2, 2, 3)


In [27]:
# arange
array = np.arange(0,10,2)
print(array)

# linspace

linsp = np.linspace(0,2,6)
print(linsp)

[0 2 4 6 8]
[0.  0.4 0.8 1.2 1.6 2. ]


In [30]:
one_arr = np.ones((3,4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
one_arr.ndim

2

In [32]:
zero_arr = np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
dia = np.eye(4)  #return 2D array in diagonal with 1
dia

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
diago = np.diag([3,9,4,1])  # return array with given diagonal
diago

array([[3, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 1]])

In [36]:
#array Random values

rand_arr = np.random.rand(5)
print(rand_arr)

[0.20466887 0.20854086 0.21088353 0.72750272 0.61765624]


In [37]:
#array Random values  : : Return a sample (or samples) from the "standard normal" distribution.

rand_arr = np.random.randn(5)   
print(rand_arr)

[ 0.31830738 -2.18331445  0.93567587 -0.59162181  0.14498012]


In [39]:
#Return random integers from `low` (inclusive) to `high` (exclusive)
rand_arr = np.random.randint(1, 100 , size= 10)
print(rand_arr)

[49 12 17 57 66 26 48 96 63 99]


In [41]:
#access array via index
print(array)
array[3]

[0 2 4 6 8]


6

In [44]:
print(array_2d)
array_2d[1,2]

[[1 2 3]
 [5 6 7]]


7

In [45]:
#slice 
rand_arr[:4]

array([49, 12, 17, 57])

In [46]:
rand_arr[1:6:2] # startindex:endindex:step

array([12, 57, 26])

In [50]:
#shared memory v/s Copy

#shared memory

a =np.arange(10)
print("Array 'a' will be :::  ",a)

b = a[::2]
print("Array 'b' will be :::  ",b)

print('Does a and b sared memory :: ',np.shares_memory(a,b))

#Proof
b[0] = 10

print("Array 'b', after change :::  ", b)
print("Array 'a', after change 'b' :::  ", a)

Array 'a' will be :::   [0 1 2 3 4 5 6 7 8 9]
Array 'b' will be :::   [0 2 4 6 8]
Does a and b sared memory ::  True
Array 'b', after change :::   [10  2  4  6  8]
Array 'a', after change 'b' :::   [10  1  2  3  4  5  6  7  8  9]


In [51]:
#copy

a =np.arange(10)
print("Array 'a' will be :::  ",a)

b = a[::2].copy()
print("Array 'b' will be :::  ",b)

print('Does a and b sared memory :: ',np.shares_memory(a,b))

#Proof
b[0] = 10

print("Array 'b', after change :::  ", b)
print("Array 'a', after change 'b' :::  ", a)

Array 'a' will be :::   [0 1 2 3 4 5 6 7 8 9]
Array 'b' will be :::   [0 2 4 6 8]
Does a and b sared memory ::  False
Array 'b', after change :::   [10  2  4  6  8]
Array 'a', after change 'b' :::   [0 1 2 3 4 5 6 7 8 9]


In [52]:
# masking 
a = np.random.randint(1,100,20)
print(a)
mask = (a % 2 == 0 )
print(a[mask])     # fetch those element which divided by 2


[15 56 94 40 32 96 12 51 54 31 14 82 24 37 70 32 20 72 56 65]
[56 94 40 32 96 12 54 14 82 24 70 32 20 72 56]


In [53]:
a[mask] = -1   # replace those element which divided by 2 with -1
print(a)

[15 -1 -1 -1 -1 -1 -1 51 -1 31 -1 -1 -1 37 -1 -1 -1 -1 -1 65]


In [56]:
# use index

a = np.random.randint(1,100,20)
print(a)

print(a[[3,2,7,9,1,3,4,4,2,7,1,1]])

[37 91 45 17 84 24 30 46 62 16 33 89 68 89 87 50 71 41 58 48]
[17 45 46 16 91 17 84 84 45 46 91 91]


In [57]:
# Basic Operation

arr = np.array([1,2,3,4])
arr+1

array([2, 3, 4, 5])

In [58]:
#multiple (.dot multi)

arr2 = np.array([1,2,3,4])

arr*arr2

array([ 1,  4,  9, 16])

In [60]:
#matrix multiplication

arr.dot(arr2)  # summation (arr[i]*arr2[i]) where i = 0 to n

30

In [63]:
A = np.array([[4,9,9],[9,1,6],[9,2,3]])   # 3*3

B = np.array([[2,2],[5,7],[4,4]])     #3*2

In [64]:
#way1
np.dot(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [65]:
#way2
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [66]:
#way3
C = A@B
C

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [70]:
# element wise comparision

arr1 = np.array([1,2,3,4])
arr2 = np.array([9,2,5,4])
arr3 = np.array([1,2,3,4])

arr1 == arr2

array([False,  True, False,  True])

In [71]:
#array wise comparision

np.array_equal(arr1,arr2)

False

In [72]:
np.array_equal(arr1,arr3)

True

In [75]:
# logical operation
arr1 = np.array([1,0,1,0])
arr2 = np.array([0,0,1,1])

np.logical_or(arr1, arr2)

array([ True, False,  True,  True])

In [76]:
np.logical_and(arr1, arr2)

array([False, False,  True, False])

In [77]:
# Summation

In [78]:
arr= np.array([1,2,3,4])    #1D arry

np.sum(arr)

10

In [85]:
arr= np.array([[7,3,3,4],[1,2,3,5]])   #2D array

print(np.sum(arr))   # all element sum

print(np.sum(arr, axis = 0))   # all element sum col-wise

print(np.sum(arr, axis = 1))   # all element sum row-wise

28
[8 5 6 9]
[17 11]


In [90]:
# min-max

# all element
print("All element min-max")
print(arr.min())   
print(arr.max())

# rol-wise
print("row-wise element min-max")
print(arr.min(axis =1))
print(arr.max(axis =1))

# rol-wise
print("col-wise element min-max")
print(arr.min(axis =0))
print(arr.max(axis =0))

All element min-max
1
7
row-wise element min-max
[3 1]
[7 5]
col-wise element min-max
[1 2 3 4]
[7 3 3 5]


In [91]:
# Index of min-max

print(arr.argmax())
print(arr.argmin())

0
4


In [99]:
#Basic stats 

print("MEAN  ::  ",np.mean(arr))
print("MEDIAN ::  ",np.median(arr))
print("STD DERIVA  ::  ",np.std(arr))
print("VARIANCE  ::  ",np.var(arr))


print("MEAN  ::  ",np.mean(arr, axis = 0))
print("MEDIAN ::  ",np.median(arr, axis = 0))
print("STD DERIVA  ::  ",np.std(arr, axis = 0))
print("STD DERIVA  ::  ",np.var(arr, axis = 0))

MEAN  ::   3.5
MEDIAN ::   3.0
STD DERIVA  ::   1.7320508075688772
VARIANCE  ::   3.0
MEAN  ::   [4.  2.5 3.  4.5]
MEDIAN ::   [4.  2.5 3.  4.5]
STD DERIVA  ::   [3.  0.5 0.  0.5]
STD DERIVA  ::   [9.   0.25 0.   0.25]


In [114]:
# Re - Shape array

a = np.arange(0,10,1)
print(a)

print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [115]:
a_2d = a.reshape(2,5)
print(a_2d)

print(a_2d.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [117]:
a_newaxis = a[: , np.newaxis]
print(a_newaxis)

print(a_newaxis.shape)


a_newaxis = a[np.newaxis, :]
print(a_newaxis)

print(a_newaxis.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [118]:
arr_2d = np.array([[1,8,3],[5,7,2]])
print(arr_2d)
print(arr_2d.shape)


# Ravel

new_arr = arr_2d.ravel()    # flatten 2-D array to 1-D
print(new_arr)
print(new_arr.shape)


[[1 8 3]
 [5 7 2]]
(2, 3)
[1 8 3 5 7 2]
(6,)


In [119]:
# Sorting 
arr =np.array([7,3,9,4,6,0])

np.sort(arr)

array([0, 3, 4, 6, 7, 9])

In [121]:
sorted_index = np.argsort(arr)
sorted_index

array([5, 1, 3, 4, 0, 2], dtype=int64)

In [122]:
arr[sorted_index]

array([0, 3, 4, 6, 7, 9])